/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micalculatortest;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws MalformedURLException, InterruptedException {

        System.out.println(new App().getGreeting());

        // Set the capabilities using UiAutomator2Options
        UiAutomator2Options options = new UiAutomator2Options();
        options.setAutomationName("UiAutomator2"); // Appium automation engine
        options.setPlatformName("Android"); // Mobile OS
        options.setDeviceName("Android Emulator"); // Emulator/device name
        options.setAppPackage("com.miui.calculator");
        options.setAppActivity("com.miui.calculator.cal.CalculatorActivity");

        // Appium server URL
        URL appiumServerUrl = new URL("http://127.0.0.1:4723/");

        // Create AndroidDriver with updated constructor
        AndroidDriver driver = new AndroidDriver(appiumServerUrl, options);

        Thread.sleep(3000);

        System.out.println("successfully open calculator");

        WebElement digit_9 = driver.findElement(By.id("com.miui.calculator:id/digit_9"));
        WebElement digit_7 = driver.findElement(By.id("com.miui.calculator:id/digit_7"));
        WebElement button_plus = driver.findElement(By.id("com.miui.calculator:id/op_add"));
        WebElement button_equal = driver.findElement(By.id("com.miui.calculator:id/btn_equal_s"));
        
        digit_9.click();
        Thread.sleep(1000);
        
        button_plus.click();
        Thread.sleep(1000);
        
        digit_7.click();
        Thread.sleep(1000);
        
        button_equal.click();
        Thread.sleep(1000);
        
        WebElement answer_area = driver.findElement(By.id("com.miui.calculator:id/result"));
        String answer_text = answer_area.getText();
        System.out.println(answer_text.contains("= 16"));
        System.out.println(answer_text);

        // Quit the driver
        driver.quit();

    }

}
